services:
  stalwart-mail:
    image: stalwart-fdb:latest
    volumes:
      - ./stalwart-mail:/opt/stalwart-mail
      - ./fdb/fdb.cluster:/etc/foundationdb/fdb.cluster:ro
    restart: unless-stopped
    depends_on:
      - fdb
      - minio
    ports:
      - 10443:443
      - 8080:8080
      - 1025:25
      - 10587:587
      - 10465:465
        #- 143:143
      - 10993:993
      - 4190:4190
        #- 110:110
        #- 995:995
      - 1179:1179/udp

  fdb:
    image: foundationdb/foundationdb:${FDB_VERSION}
    environment:
      FDB_COORDINATOR: ${FDB_COORDINATOR}
      FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
      FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}
    volumes:
      - ./fdb/data:/var/fdb/data
      - ./fdb/logs:/var/fdb/logs
      - ./fdb/fdb.cluster:/var/fdb/fdb.cluster
      - ./fdb/backup:/backup
    network_mode: "host"
    entrypoint: /usr/bin/fdbserver
    command:
      - "--cluster_file=$FDB_CLUSTER_FILE"
      - "--listen-address=$FDB_PUBLIC_IP:4500"
      - "--public-address=$FDB_PUBLIC_IP:4500"
      - "--datadir=/var/fdb/data"        # Must match volume mount target
      - "--logdir=/var/fdb/logs"         # Must match volume mount target
      - "--locality-zoneid=$FDB_HOST_HOSTNAME"
      - "--locality-machineid=$FDB_HOST_HOSTNAME"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: always

  minio:
    image: minio/minio:${MINIO_RELEASE}
    volumes:
      - ./minio/data1:/data1
      - ./minio/data2:/data2
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: public
    command: server --console-address ":9001" 
      http://server1:9000/data1
      http://server1:9000/data2
      http://server2:9000/data1 
      http://server2:9000/data2 
      http://server3:9000/data1 
      http://server3:9000/data2 
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/etc:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - node-exporter
      - cadvisor
      - fdb-exporter

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    # Required for scraping host metrics
    pid: host

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--housekeeping_interval=30s"
    ports:
      # Use 8081 to avoid conflict with stalwart-mail's 8080 if exposed on host
      - 8081:8080
    # Required for scraping container metrics
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg

  fdb-exporter:
    image: clevercloud/fdbexporter:2.0.1-7.3.63
    depends_on:
      - fdb
    restart: always
    environment:
      FDB_COORDINATOR: ${FDB_COORDINATOR}
      FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
      FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}
    env_file:
      - .env
    ports:
      - 9188:9090

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Add volumes for SSL certs if using HTTPS
      # - ./certs:/etc/nginx/certs:ro
      - ./nginx/logs:/var/log/nginx # Mount logs (optional)
    network_mode: host
    restart: always
