global:
  #scrape_interval: 120s # Default scrape interval
  scrape_interval: 60s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus itself

  - job_name: 'node-exporter'
    static_configs:
      # Use the internal docker network hostname 'node-exporter'
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      # Use the internal docker network hostname 'cadvisor' and its internal port 8080
      - targets: ['cadvisor:8080']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['server1:9000']

  - job_name: 'stalwart-mail'
    metrics_path: /metrics/prometheus
    scheme: http
    static_configs:
      - targets: ['stalwart-mail:8080']

  - job_name: 'fdb_exporter'
    fallback_scrape_protocol: PrometheusText0.0.4
    static_configs:
      - targets: ['server1:9188']
